### ISSUE TITLE
Test the terraform scripts with the latest version

### ISSUE THREAD

**Issue by mkumatag** [ppc64le-cloud/kubetest2-plugins#28]
TF script present here: https://github.com/ppc64le-cloud/kubetest2-plugins/tree/master/data/data/powervs

Once it is done, will use the new version of all-in-one get pushed here: https://github.com/ppc64le-cloud/test-infra/issues/142

**Comment by RagniGarg97** [comment]
Getting below error while installing terraform version v0.14.7
```
# go get github.com/hashicorp/terraform@v0.14.7
go: finding module for package github.com/hashicorp/terraform/terraform
go: finding module for package github.com/hashicorp/terraform/builtin/providers/terraform
go: finding module for package k8s.io/client-go/kubernetes/typed/coordination/v1
go: finding module for package github.com/gregjones/httpcache/diskcache
go: finding module for package github.com/gregjones/httpcache
go: finding module for package github.com/gophercloud/utils/terraform/auth
go: finding module for package k8s.io/api/admissionregistration/v1alpha1
go: finding module for package github.com/peterbourgon/diskv
go: found k8s.io/client-go/kubernetes/typed/coordination/v1 in k8s.io/client-go v11.0.0+incompatible
go: found github.com/gophercloud/utils/terraform/auth in github.com/gophercloud/utils v0.0.0-20210216074907-f6de111f2eae
go: found github.com/gregjones/httpcache in github.com/gregjones/httpcache v0.0.0-20190611155906-901d90724c79
go: found github.com/gregjones/httpcache/diskcache in github.com/gregjones/httpcache v0.0.0-20190611155906-901d90724c79
go: found github.com/peterbourgon/diskv in github.com/peterbourgon/diskv v2.0.1+incompatible
go: finding module for package github.com/hashicorp/terraform/terraform
go: finding module for package github.com/hashicorp/terraform/builtin/providers/terraform
go: finding module for package github.com/hashicorp/terraform/builtin/providers/terraform
go: finding module for package github.com/hashicorp/terraform/terraform
go: finding module for package github.com/hashicorp/terraform/terraform
go: finding module for package github.com/hashicorp/terraform/builtin/providers/terraform
go/pkg/mod/github.com/hashicorp/terraform@v0.14.7/command/meta_providers.go:16:2: module github.com/hashicorp/terraform@latest found (v0.14.7), but does not contain package github.com/hashicorp/terraform/builtin/providers/terraform
go/pkg/mod/github.com/hashicorp/terraform@v0.14.7/command/clistate/local_state.go:16:2: module github.com/hashicorp/terraform@latest found (v0.14.7), but does not contain package github.com/hashicorp/terraform/terraform

**Comment by mkumatag** [comment]
see if we need to just clone the code and build it, more information - https://github.com/hashicorp/terraform/blob/main/.github/CONTRIBUTING.md#terraform-clicore-development-environment
 
----- Original message -----From: RagniGarg97 <notifications@github.com>To: ppc64le-cloud/kubetest2-plugins <kubetest2-plugins@noreply.github.com>Cc: Manjunath Kumatagi <mkumatag@in.ibm.com>, Author <author@noreply.github.com>Subject: [EXTERNAL] Re: [ppc64le-cloud/kubetest2-plugins] Test the terraform scripts with the latest version (#28)Date: Mon, Mar 8, 2021 12:23 PM  
 
Getting below error while installing terraform version v0.14.7
# go get github.com/hashicorp/terraform@v0.14.7go: finding module for package github.com/hashicorp/terraform/terraformgo: finding module for package github.com/hashicorp/terraform/builtin/providers/terraformgo: finding module for package k8s.io/client-go/kubernetes/typed/coordination/v1go: finding module for package github.com/gregjones/httpcache/diskcachego: finding module for package github.com/gregjones/httpcachego: finding module for package github.com/gophercloud/utils/terraform/authgo: finding module for package k8s.io/api/admissionregistration/v1alpha1go: finding module for package github.com/peterbourgon/diskvgo: found k8s.io/client-go/kubernetes/typed/coordination/v1 in k8s.io/client-go v11.0.0+incompatiblego: found github.com/gophercloud/utils/terraform/auth in github.com/gophercloud/utils v0.0.0-20210216074907-f6de111f2eaego: found github.com/gregjones/httpcache in github.com/gregjones/httpcache v0.0.0-20190611155906-901d90724c79go: found github.com/gregjones/httpcache/diskcache in github.com/gregjones/httpcache v0.0.0-20190611155906-901d90724c79go: found github.com/peterbourgon/diskv in github.com/peterbourgon/diskv v2.0.1+incompatiblego: finding module for package github.com/hashicorp/terraform/terraformgo: finding module for package github.com/hashicorp/terraform/builtin/providers/terraformgo: finding module for package github.com/hashicorp/terraform/builtin/providers/terraformgo: finding module for package github.com/hashicorp/terraform/terraformgo: finding module for package github.com/hashicorp/terraform/terraformgo: finding module for package github.com/hashicorp/terraform/builtin/providers/terraformgo/pkg/mod/github.com/hashicorp/terraform@v0.14.7/command/meta_providers.go:16:2: module github.com/hashicorp/terraform@latest found (v0.14.7), but does not contain package github.com/hashicorp/terraform/builtin/providers/terraformgo/pkg/mod/github.com/hashicorp/terraform@v0.14.7/command/clistate/local_state.go:16:2: module github.com/hashicorp/terraform@latest found (v0.14.7), but does not contain package github.com/hashicorp/terraform/terraform

**Comment by RagniGarg97** [comment]
> see if we need to just clone the code and build it, more information - https://github.com/hashicorp/terraform/blob/main/.github/CONTRIBUTING.md#terraform-clicore-development-environment   ----- Original message -----From: RagniGarg97 <notifications@github.com>To: ppc64le-cloud/kubetest2-plugins <kubetest2-plugins@noreply.github.com>Cc: Manjunath Kumatagi <mkumatag@in.ibm.com>, Author <author@noreply.github.com>Subject: [EXTERNAL] Re: [ppc64le-cloud/kubetest2-plugins] Test the terraform scripts with the latest version (#28)Date: Mon, Mar 8, 2021 12:23 PM    Getting below error while installing terraform version v0.14.7 # go get github.com/hashicorp/terraform@v0.14.7go: finding module for package github.com/hashicorp/terraform/terraformgo: finding module for package github.com/hashicorp/terraform/builtin/providers/terraformgo: finding module for package k8s.io/client-go/kubernetes/typed/coordination/v1go: finding module for package github.com/gregjones/httpcache/diskcachego: finding module for package github.com/gregjones/httpcachego: finding module for package github.com/gophercloud/utils/terraform/authgo: finding module for package k8s.io/api/admissionregistration/v1alpha1go: finding module for package github.com/peterbourgon/diskvgo: found k8s.io/client-go/kubernetes/typed/coordination/v1 in k8s.io/client-go v11.0.0+incompatiblego: found github.com/gophercloud/utils/terraform/auth in github.com/gophercloud/utils v0.0.0-20210216074907-f6de111f2eaego: found github.com/gregjones/httpcache in github.com/gregjones/httpcache v0.0.0-20190611155906-901d90724c79go: found github.com/gregjones/httpcache/diskcache in github.com/gregjones/httpcache v0.0.0-20190611155906-901d90724c79go: found github.com/peterbourgon/diskv in github.com/peterbourgon/diskv v2.0.1+incompatiblego: finding module for package github.com/hashicorp/terraform/terraformgo: finding module for package github.com/hashicorp/terraform/builtin/providers/terraformgo: finding module for package github.com/hashicorp/terraform/builtin/providers/terraformgo: finding module for package github.com/hashicorp/terraform/terraformgo: finding module for package github.com/hashicorp/terraform/terraformgo: finding module for package github.com/hashicorp/terraform/builtin/providers/terraformgo/pkg/mod/github.com/hashicorp/terraform@v0.14.7/command/meta_providers.go:16:2: module github.com/hashicorp/terraform@latest found (v0.14.7), but does not contain package github.com/hashicorp/terraform/builtin/providers/terraformgo/pkg/mod/github.com/hashicorp/terraform@v0.14.7/command/clistate/local_state.go:16:2: module github.com/hashicorp/terraform@latest found (v0.14.7), but does not contain package github.com/hashicorp/terraform/terraform —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

```
# terraform --version
Terraform v0.14.8-dev

**Comment by RagniGarg97** [comment]
```
# kubetest2 tf --powervs-api-key <api-key> --powervs-dns k8s-tests --powervs-image-name centos-83-02182021 --powervs-region lon --powervs-zone lon04 --powervs-service-id 7845d372-d4e1-46b8-91fc-41051c984601 --powervs-ssh-key ragni-key --ssh-private-key /workspace/ssh-private --build-version "v1.19.2" --release-marker release/v1.19.2 --s3-server "storage.googleapis.com" --bucket "kubernetes-release"  --directory "release" --cluster-name ragni-cluster11 --up --down --ignore-cluster-dir true --auto-approve --ignore-destroy-errors  --powervs-memory 32 --test=ginkgo -- --parallel 10 --flake-attempts 2 --test-package-bucket kubernetes-release --test-package-dir release --test-package-version "v1.19.2" --focus-regex='should\ find\ a\ service' 2>&1 | tee new_log.txt
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/null...
- Finding hashicorp/ibm versions matching ">= 1.9.0"...

Warning: Version constraints inside provider configuration blocks are deprecated

  on ragni-cluster11/provider.tf line 2, in provider "ibm":
   2:   version = ">= 1.9.0"

Terraform 0.13 and earlier allowed provider version constraints inside the
provider configuration block, but that is now deprecated and will be removed
in a future version of Terraform. To silence this warning, move the provider
version constraint into the required_providers block.


Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider hashicorp/ibm:
provider registry registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/ibm

If you have just upgraded directly from Terraform v0.12 to Terraform v0.14
then please upgrade to Terraform v0.13 first and follow the upgrade guide for
that release, which might help you address this problem.


Error: Incompatible provider version

Provider registry.terraform.io/hashicorp/null v3.1.0 does not have a package
available for your current platform, linux_ppc64le.

Provider releases are separate from Terraform CLI releases, so not all
providers are available for all platforms. Other versions of this provider may
have different platforms supported.

Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/ibm versions matching ">= 1.9.0"...
- Finding latest version of hashicorp/null...

Warning: Version constraints inside provider configuration blocks are deprecated

  on ragni-cluster11/provider.tf line 2, in provider "ibm":
   2:   version = ">= 1.9.0"

Terraform 0.13 and earlier allowed provider version constraints inside the
provider configuration block, but that is now deprecated and will be removed
in a future version of Terraform. To silence this warning, move the provider
version constraint into the required_providers block.


Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider hashicorp/ibm:
provider registry registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/ibm

If you have just upgraded directly from Terraform v0.12 to Terraform v0.14
then please upgrade to Terraform v0.13 first and follow the upgrade guide for
that release, which might help you address this problem.


Error: Incompatible provider version

Provider registry.terraform.io/hashicorp/null v3.1.0 does not have a package
available for your current platform, linux_ppc64le.

Provider releases are separate from Terraform CLI releases, so not all
providers are available for all platforms. Other versions of this provider may
have different platforms supported.

Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/ibm versions matching ">= 1.9.0"...
- Finding latest version of hashicorp/null...

Warning: Version constraints inside provider configuration blocks are deprecated

  on ragni-cluster11/provider.tf line 2, in provider "ibm":
   2:   version = ">= 1.9.0"

Terraform 0.13 and earlier allowed provider version constraints inside the
provider configuration block, but that is now deprecated and will be removed
in a future version of Terraform. To silence this warning, move the provider
version constraint into the required_providers block.


Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider hashicorp/ibm:
provider registry registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/ibm

If you have just upgraded directly from Terraform v0.12 to Terraform v0.14
then please upgrade to Terraform v0.13 first and follow the upgrade guide for
that release, which might help you address this problem.


Error: Incompatible provider version

Provider registry.terraform.io/hashicorp/null v3.1.0 does not have a package
available for your current platform, linux_ppc64le.

Provider releases are separate from Terraform CLI releases, so not all
providers are available for all platforms. Other versions of this provider may
have different platforms supported.

Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/null...
- Finding hashicorp/ibm versions matching ">= 1.9.0"...

Warning: Version constraints inside provider configuration blocks are deprecated

  on ragni-cluster11/provider.tf line 2, in provider "ibm":
   2:   version = ">= 1.9.0"

Terraform 0.13 and earlier allowed provider version constraints inside the
provider configuration block, but that is now deprecated and will be removed
in a future version of Terraform. To silence this warning, move the provider
version constraint into the required_providers block.


Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider hashicorp/ibm:
provider registry registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/ibm

If you have just upgraded directly from Terraform v0.12 to Terraform v0.14
then please upgrade to Terraform v0.13 first and follow the upgrade guide for
that release, which might help you address this problem.


Error: Incompatible provider version

Provider registry.terraform.io/hashicorp/null v3.1.0 does not have a package
available for your current platform, linux_ppc64le.

Provider releases are separate from Terraform CLI releases, so not all
providers are available for all platforms. Other versions of this provider may
have different platforms supported.

terraform.Output: 
terraform.Output error: failed to initialize Terraform
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/ibm versions matching ">= 1.9.0"...
- Finding latest version of hashicorp/null...

Warning: Version constraints inside provider configuration blocks are deprecated

  on ragni-cluster11/provider.tf line 2, in provider "ibm":
   2:   version = ">= 1.9.0"

Terraform 0.13 and earlier allowed provider version constraints inside the
provider configuration block, but that is now deprecated and will be removed
in a future version of Terraform. To silence this warning, move the provider
version constraint into the required_providers block.


Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider hashicorp/ibm:
provider registry registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/ibm

If you have just upgraded directly from Terraform v0.12 to Terraform v0.14
then please upgrade to Terraform v0.13 first and follow the upgrade guide for
that release, which might help you address this problem.


Error: Incompatible provider version

Provider registry.terraform.io/hashicorp/null v3.1.0 does not have a package
available for your current platform, linux_ppc64le.

Provider releases are separate from Terraform CLI releases, so not all
providers are available for all platforms. Other versions of this provider may
have different platforms supported.

I0308 01:00:44.889833   45903 deployer.go:248] terraform.Destroy failed: failed to initialize Terraform
Error: Terraform Apply failed. Error: failed to initialize Terraform

**Comment by mkumatag** [comment]
> Error: Incompatible provider version
> 
> Provider registry.terraform.io/hashicorp/null v3.1.0 does not have a package
> available for your current platform, linux_ppc64le.
> 
> Provider releases are separate from Terraform CLI releases, so not all
> providers are available for all platforms. Other versions of this provider may
> have different platforms supported.
> 
> Initializing modules...
> 
> Initializing the backend...
> 
> Initializing provider plugins...
> - Finding hashicorp/ibm versions matching ">= 1.9.0"...
> - Finding latest version of hashicorp/null...
> 
> Warning: Version constraints inside provider configuration blocks are deprecated
> 
>   on ragni-cluster11/provider.tf line 2, in provider "ibm":
>    2:   version = ">= 1.9.0"

You might need to work on making these things work with the latest terraform version, rightnow we have an older version of ibmcloud tf module which is not really compatible with the latest one.

**Comment by mkumatag** [comment]
> # terraform --version
> Terraform v0.14.8-dev

not sure why `-dev`, make sure you checkout the latest release and build the binary from that instead of the master branch.

**Comment by RagniGarg97** [comment]
Terraform plugins are not available on Power systems, we need to compile them manually and configure TF to use that on Power.

After doing that also, we are getting the below errors:
```
Initializing modules...
- master in instance
- workers in instance

Initializing the backend...

Initializing provider plugins...
- Finding ibm-cloud/ibm versions matching "1.11.2"...
- Finding hashicorp/null versions matching "~> 2.1"...
- Finding latest version of hashicorp/ibm...

Error: Failed to install provider

Error while installing ibm-cloud/ibm v1.11.2: provider
registry.terraform.io/ibm-cloud/ibm 1.11.2 is not available for linux_ppc64le


Error: Failed to install provider

Error while installing hashicorp/null v2.1.2: provider
registry.terraform.io/hashicorp/null 2.1.2 is not available for linux_ppc64le


Error: Failed to install provider

Error while installing hashicorp/ibm: provider registry registry.terraform.io
does not have a provider named registry.terraform.io/hashicorp/ibm

**Comment by mkumatag** [comment]
> Terraform plugins are not available on Power systems, we need to compile them manually and configure TF to use that on Power.
> 
> After doing that also, we are getting the below errors:

@yussufsh any suggestions?

**Comment by yussufsh** [comment]
Once you compile and keep the binaries on local file system you can use `terraform init --plugin-dir <path>` option.

Please see the similar instructions we have for ocp deployments on Power at https://github.com/ocp-power-automation/terraform-providers-power#instructions.

You can get the TF binary for Power from unicamp site as well.

**Comment by mkumatag** [comment]
> Once you compile and keep the binaries on local file system you can use `terraform init --plugin-dir <path>` option.

Do we any other way? like setting environment variable to say where to look for the plugins etc?

**Comment by yussufsh** [comment]
See https://www.terraform.io/docs/cli/config/config-file.html#implied-local-mirror-directories to know all the locations allowed to store the plugins as per your OS.

Also, for explicit mirror path see https://www.terraform.io/docs/cli/config/config-file.html#explicit-installation-method-configuration where you can control which providers to look at in mirror and which to exclude. This becomes more complex and I recommend to stick with the former implied paths for storing the plugins.

Best approach is to use the `init` command to load from specific path as mentioned before.

**Comment by RagniGarg97** [comment]
> Terraform plugins are not available on Power systems, we need to compile them manually and configure TF to use that on Power.
> 
> After doing that also, we are getting the below errors:
> 
> ```
> Initializing modules...
> - master in instance
> - workers in instance
> 
> Initializing the backend...
> 
> Initializing provider plugins...
> - Finding ibm-cloud/ibm versions matching "1.11.2"...
> - Finding hashicorp/null versions matching "~> 2.1"...
> - Finding latest version of hashicorp/ibm...
> 
> Error: Failed to install provider
> 
> Error while installing ibm-cloud/ibm v1.11.2: provider
> registry.terraform.io/ibm-cloud/ibm 1.11.2 is not available for linux_ppc64le
> 
> 
> Error: Failed to install provider
> 
> Error while installing hashicorp/null v2.1.2: provider
> registry.terraform.io/hashicorp/null 2.1.2 is not available for linux_ppc64le
> 
> 
> Error: Failed to install provider
> 
> Error while installing hashicorp/ibm: provider registry registry.terraform.io
> does not have a provider named registry.terraform.io/hashicorp/ibm
> ```

This error is resolved if we use the following directory structure for keeping the required plugins:
```
root@terraform-pod:/workspace/.terraform# find | sed 's|[^/]*/|- |g'
.
- modules
- - modules.json
- plugins
- - selections.json
- - registry.terraform.io
- - - hashicorp
- - - - ibm
- - - - - 1.13.1
- - - - - - linux_ppc64le
- - - - - - - terraform-provider-ibm
- - - - null
- - - - - 2.1.0
- - - - - - linux_ppc64le
- - - - - - - terraform-provider-null

**Comment by yussufsh** [comment]
`.terraform` folder will be overwritten if someone runs `terraform init` again. You should not be updating this directory manually.

**Comment by RagniGarg97** [comment]
@yussufsh If we are using terraform (v0.12.29) , it looks for the plugins in `.terraform.d` folder. But if we use terraform (version 0.13.0), it looks for `.terraform` . Is my understanding correct?

**Comment by yussufsh** [comment]
For both version `terraform init` will download the plugins in `.terraform` directory. Also the structure is different.

As I had mentioned you should not be creating this directory manually.
You should keep the plugins in external mirror directory with the required structure.

TF 0.12: ~/.terraform.d/plugins
TF 0.13: Terraform will use ~/.local/share/terraform/plugins, /usr/local/share/terraform/plugins, and /usr/share/terraform/plugins. 


Above is one way.. another way is to use `terraform init --plugin-dir <path>`

For explanation and directory structure for TF 0.13 see the upgrade guide. https://www.terraform.io/upgrade-guides/0-13.html#new-filesystem-layout-for-local-copies-of-providers

**Comment by Rajalakshmi-Girish** [comment]
We are currently facing the below error on trying to create VM on PowerVS:
```
err: {"description":"an error has occurred; please try again: unable to get network, subnet, and possibly public network cidr for network today-raji2-pub-net on cloud instance 7031b049297e4588a3eafb21335d6a2b","error":"internal server error"}
```
@yussufsh Have you come across this anytime? Any pointers to debug please:
Things we verified:
1. Able to create a network resource alone with terraform 0.13. (.tf script with only network resource)
2. Enabled TF_LOG=TRACE and checked for info in the trace.
```
2021-03-25T05:16:55.677-0700 [DEBUG] plugin.terraform-provider-ibm: 2021/03/25 05:16:55 Failed to perform the operation... [GET /pcloud/v1/cloud-instances/{cloud_instance_id}/networks/{network_id}][500] pcloudNetworksGetInternalServerError  &{Code:0 Description:an error has occurred; please try again: unable to get network, subnet, and possibly public network cidr for network today-raji2-pub-net on cloud instance 7031b049297e4588a3eafb21335d6a2b Error:internal server error Message:}
```
3. Looked for any commits in `ocp-power-automation/ocp4-upi-powervs` specific to terraform version upgrade - _Didn't find anything specific!_
4. Compared our .tf scripts with the ocp current repo to find any additions. - _Our scripts look-alike to the ones in ocp except the condition to look for existing network when network name is passed as argument._
https://github.com/ppc64le-cloud/kubetest2-plugins/blob/master/data/data/powervs/instance/main.tf is the script that throws above error.

**Comment by yussufsh** [comment]
Could be just the dependency issue. Public network is not created completely till used by the given resource.

**Comment by Rajalakshmi-Girish** [comment]
> 
> 
> Could be just the dependency issue. Public network is not created completely till used by the given resource.

Do you mean provider binaries when you say dependency?

**Comment by Rajalakshmi-Girish** [comment]
We tried using the 1.21.0 and 1.3.1 versions of `terraform-provider-ibm`
2.1.0 version of `terraform-provider-null`

**Comment by yussufsh** [comment]
No, the resource dependencies.

**Comment by Rajalakshmi-Girish** [comment]
> 
> 
> No, the resource dependencies.

@yussufsh So, the dependent resource for VM is a network. _The same .tf scripts worked when we used terraform 0.12._
Can you please hint on what could hinder network creation?

**Snippet of main.tf from where we run `terraform` command.**
```
data "ibm_pi_network" "existing_net" {
  count                = var.powervs_network_name == "" ? 0 : 1
  pi_network_name      = var.powervs_network_name
  pi_cloud_instance_id = var.powervs_service_id
}

resource "ibm_pi_network" "public_network" {
  count                   = var.powervs_network_name == "" ? 1 : 0
  pi_network_name           = "${var.cluster_name}-pub-net"
  pi_cloud_instance_id      = var.powervs_service_id
  pi_network_type           = "pub-vlan"
  pi_dns = [ "9.9.9.9", "8.8.8.8"]
}

module "master" {
  source = "./instance"

  ibmcloud_api_key = var.powervs_api_key
  image_name = var.powervs_image_name
  memory = var.powervs_memory
  networks = [var.powervs_network_name == "" ? ibm_pi_network.public_network[0].pi_network_name : data.ibm_pi_network.existing_net[0].pi_network_name]
  powervs_service_instance_id = var.powervs_service_id
  processors = var.powervs_processors
  ssh_key_name = var.powervs_ssh_key
  vm_name = "${var.cluster_name}-master"
  ibmcloud_region = var.powervs_region
  ibmcloud_zone = var.powervs_zone
}
```
**snippet of main.tf in instance module.**
```
data "ibm_pi_network" "power_networks" {
    count                = length(var.networks)
    pi_network_name      = var.networks[count.index]
    pi_cloud_instance_id = var.powervs_service_instance_id
}

data "ibm_pi_image" "power_images" {
    pi_image_name        = var.image_name
    pi_cloud_instance_id = var.powervs_service_instance_id
}

resource "ibm_pi_instance" "pvminstance" {
    count = var.instance_count
    pi_memory             = var.memory
    pi_processors         = var.processors
    pi_instance_name      = var.instance_count == 1 ? var.vm_name : "${var.vm_name}-${count.index}"
    pi_proc_type          = var.proc_type
    pi_image_id           = data.ibm_pi_image.power_images.id
    pi_network_ids        = data.ibm_pi_network.power_networks.*.id
    pi_key_pair_name      = var.ssh_key_name
    pi_sys_type           = var.system_type
    pi_cloud_instance_id = var.powervs_service_instance_id
    pi_user_data          = var.user_data
}
```

**Comment by yussufsh** [comment]
See the data source in instance module will collect data at start during refresh. It will not find the public network as it is creating later during apply. Hint: Apply will run refresh first, that will populate the data sources.

**Comment by yussufsh** [comment]
So all you need is to tell TF config in instance module to not run the data until the public network is created.

**Comment by yussufsh** [comment]
Best design change for you is not to send network name but instead directly send the id which you already have in main module.

**Comment by Rajalakshmi-Girish** [comment]
@yussufsh Thank you for the pointers. I shall do the changes and see if it gets solved.

_But how come this issue did not araise all these days when we ran using terraform 0.12_

**Comment by Rajalakshmi-Girish** [comment]
> 
> 
> Best design change for you is not to send network name but instead directly send the id which you already have in main module.

I somehow found it difficult to pass the network id from main module to the instance module :(
But was able to fix the error by adding `depends_on = [ibm_pi_network.public_network] `metadata to the module section in main.tf.
https://www.hashicorp.com/blog/terraform-0-13-brings-powerful-meta-arguments-to-modular-workflows.
Thanks a ton for the pointers :)

**Comment by mkumatag** [comment]
> But was able to fix the error by adding `depends_on = [ibm_pi_network.public_network] `metadata to the module section in main.tf.

Lets add this dependency if it is solving the problem.

**Comment by yussufsh** [comment]
> Kindly let me know if passing `network_id` to instance resource is better solution than this `depends_on` argument.

I don't prefer module dependency as this will not run the data sources during refresh. See my issue https://github.com/hashicorp/terraform/issues/26749 which did not get traction but then I had fixed it by removing the module dependency https://github.com/ocp-power-automation/ocp4-upi-powervm/issues/131.

So I will suggest not use module dependency to avoid unwanted issues later.

**Comment by yussufsh** [comment]
This is how you should read the network id form root module.
```
var.powervs_network_name == "" ? ibm_pi_network.public_network[0].network_id : data.ibm_pi_network.existing_net[0].id
```

**Comment by RagniGarg97** [comment]
we have added 
```
var.powervs_network_name == "" ? ibm_pi_network.public_network[0].network_id : data.ibm_pi_network.existing_net[0].id
```

main.tf 
```
data "ibm_pi_network" "existing_net" {
  count                = var.powervs_network_name == "" ? 0 : 1
  pi_network_name      = var.powervs_network_name
  pi_cloud_instance_id = var.powervs_service_id
}

resource "ibm_pi_network" "public_network" {
  count                   = var.powervs_network_name == "" ? 1 : 0
  pi_network_name           = "${var.cluster_name}-pub-net"
  pi_cloud_instance_id      = var.powervs_service_id
  pi_network_type           = "pub-vlan"
  pi_dns = [ "9.9.9.9", "8.8.8.8"]
}

module "master" {
  source = "./instance"

  ibmcloud_api_key = var.powervs_api_key
  image_name = var.powervs_image_name
  memory = var.powervs_memory
  networks = [var.powervs_network_name == "" ? ibm_pi_network.public_network[0].network_id : data.ibm_pi_network.existing_net[0].id]
  powervs_service_instance_id = var.powervs_service_id
  processors = var.powervs_processors
  ssh_key_name = var.powervs_ssh_key
  vm_name = "${var.cluster_name}-master"
  ibmcloud_region = var.powervs_region
  ibmcloud_zone = var.powervs_zone
}

module "workers" {
  source = "./instance"
  instance_count = var.workers_count

  ibmcloud_api_key = var.powervs_api_key
  image_name = var.powervs_image_name
  memory = var.powervs_memory
  networks = [var.powervs_network_name == "" ? ibm_pi_network.public_network[0].network_id : data.ibm_pi_network.existing_net[0].id]
  powervs_service_instance_id = var.powervs_service_id
  processors = var.powervs_processors
  ssh_key_name = var.powervs_ssh_key
  vm_name = "${var.cluster_name}-worker"
  ibmcloud_region = var.powervs_region
  ibmcloud_zone = var.powervs_zone
}

resource "null_resource" "wait-for-master-completes" {
  connection {
    type = "ssh"
    user = "root"
    host = module.master.addresses[0][0].external_ip
    private_key = file(var.ssh_private_key)
    timeout = "15m"
  }
  provisioner "remote-exec" {
    inline = [
      "cloud-init status -w"
    ]
  }
}

resource "null_resource" "wait-for-workers-completes" {
  count = var.workers_count
  connection {
    type = "ssh"
    user = "root"
    host = module.workers.addresses[count.index][0].external_ip
    private_key = file(var.ssh_private_key)
    timeout = "15m"
  }
  provisioner "remote-exec" {
    inline = [
      "cloud-init status -w"
    ]
  }
}
```
The VM is created successfully and I am able to ssh into it.
However, the cluster is not up. 
```
I0331 05:29:37.242160   94495 ansible.go:27] ansible-playbook with args: [--inventory=ragni-wed2-vm/hosts --extra-vars={"release_marker":"release/v1.19.2","build_version":"v1.19.2","s3_server":"storage.googleapis.com","bucket":"kubernetes-release","directory":"release","cluster_name":"ragni-wed2-vm","apiserver_port":992,"workers_count":0,"bootstrap_token":"3btbly.4ngwwt1cwp2flrhp","kubeconfig_path":"/root/kubetest2-plugins/ragni-wed2-vm/kubeconfig","ssh_private_key":"/root/ssh-private","extra_cert":"158.175.162.4"} ragni-wed2-vm/install-k8s.yml]
Error: failed to setKubeconfig: failed to locate the kubeconfig file: stat /root/kubetest2-plugins/ragni-wed2-vm/kubeconfig: no such file or directory
```

The ansible-playbook didn't run and therefore the kubeconfig file is not generated and set. https://github.com/ppc64le-cloud/kubetest2-plugins/blob/master/kubetest2-tf/deployer/deployer.go#L195
on printing exit code and error, we get exit code `%!(EXTRA int=0) ` and error `%!(EXTRA <nil>)`

**Comment by Rajalakshmi-Girish** [comment]
I think this issue can be closed.
https://github.ibm.com/powercloud/container-dev/issues/1452 completed it.
@mkumatag ^^
