### ISSUE TITLE
Update the go.mod

### ISSUE THREAD

**Issue by mkumatag** [ppc64le-cloud/kubetest2-plugins#54]
- Lets switch to golang 1.17
- Update the dependencies

**Comment by mkumatag** [comment]
@Rajalakshmi-Girish any updates?

**Comment by Rajalakshmi-Girish** [comment]
Done by https://github.com/ppc64le-cloud/kubetest2-plugins/pull/55 and https://github.com/ppc64le-cloud/kubetest2-plugins/pull/56 I think we can close this.
