### ISSUE TITLE
Missing test environment dependency on Terraform is overridden.

### ISSUE THREAD

**Issue by kishen-v** [ppc64le-cloud/kubetest2-plugins#65]
The `kubetest2 tf` deployer misses to check if Terraform is already installed in the test environment. In case if terraform is missing, the plugin still proceeds run and raise an error due to missing fields that are to be generated as a part of terraform apply, attributing to <nil> fields from Up(). 

The expected behaviour is to validate if terraform is installed in the environment before provisioning the cluster.

**Comment by mkumatag** [comment]
@kishen-v are you going send the fix for this issue?

**Comment by kishen-v** [comment]
@mkumatag. I will work on providing a fix for this issue.

**Comment by kishen-v** [comment]
PR with the fix for the issue has been merged to master.
