### ISSUE TITLE
Use latest golang version in the CI

### ISSUE THREAD

**Issue by mkumatag** [ppc64le-cloud/kubetest2-plugins#74]
Lets use 1.19
https://github.com/ppc64le-cloud/kubetest2-plugins/blob/3042b76aa0e469b85154efcc7b4058eaff41d943/.github/workflows/go.yml#L19

**Comment by kishen-v** [comment]
Addressed through PR https://github.com/ppc64le-cloud/kubetest2-plugins/pull/75
Changes done to pick the go version from go.mod file.

Reference: https://github.com/actions/setup-go#getting-go-version-from-the-gomod-file
